'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  polaris:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Polaris Scan
        uses: blackduck-inc/black-duck-security-scan@v2.1.1
        with:
          polaris:
            polaris_assessment_types:
              - SAST
              - SCA
          coverity:
            coverity_policy_view: Outstanding Issues
          blackduck-sca: {}
          polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
    runs-on:
      - ubuntu-latest
name: Black Duck Polaris
