'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  coverity:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Coverity Scan
        uses: blackduck-inc/black-duck-security-scan@v2.1.1
        with:
          coverity_url: ${{ vars.COVERITY_URL }}
          coverity_user: ${{ vars.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          coverity_policy_view: Outstanding Issues
    runs-on:
      - ubuntu-latest
name: Black Duck Coverity
