
name: "Software Composition Analysis"

on:
  push:
    branches: [main,release-*]
  
  pull_request:

jobs:
  sca-scans:
    uses: abyreddy-org/sca-scan-templates/.github/workflows/sca-ci.yml@main
    secrets: inherit
  