name: Black Duck Polaris
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch: 
  
jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Coverity Scan
        uses: synopsys-sig/synopsys-action@v1.13.0
        with:
          ### SCANNING: Required fields
          blackduck_url: ${{ vars.BLACKDUCK_URL }}
          blackduck_token: ${{ secrets.BLACKDUCK_TOKEN }}
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          project_name: ${{ vars.PROJECT_NAME }}
          project_version: ${{ vars.PROJECT_VERSION }}
          project_version_name: ${{ vars.PROJECT_VERSION_NAME }}
          project_version_description: ${{ vars.PROJECT_VERSION_DESCRIPTION }}
